import { Post } from '@/models/Post'
import { GetServerSideProps } from 'next'
import Head from 'next/head'
import Link from 'next/link'

type Props = {
  posts: Post[]
}

export default function Home({posts}: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Home</h1>
        {posts.map(post => (
          <div key={post.id}>
            <Link href={"/posts/" + post.id}>
              <h2>{post.title}</h2>
            </Link>
            <p>{post.body}</p>
          </div>
        ))}
      </div>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  const response = await fetch(`https://jsonplaceholder.typicode.com/posts`)
  const posts: Post[] = await response.json()

  return {
    props: {
      posts,
    },
  }
}